repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7  # ruff version
    hooks:
      - id: ruff  # run the linter
        args: [ --fix ]
      - id: ruff-format  # run the formatter