name: 'Run full Goalie test suite'

on:
  # Run test suite whenever main is updated, i.e., a PR is merged
  push:
    branches:
      - main

  # Run test suite every Sunday at 1AM
  schedule:
    - cron: '0 1 * * 0'

concurrency:
  # Cancel jobs running if new commits are pushed
  group: >
    ${{ github.workflow }}-
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Full test suite'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mesh-adaptation/firedrake-parmmg:latest
      options: --user root
    steps:
      - name: 'Check out the repo'
        id: checkout
        uses: actions/checkout@v4

      - name: 'Cleanup'
        if: ${{ always() }}
        run: |
          cd ..
          rm -rf build

      - name: 'Setup Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 'Install Goalie'
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip uninstall -y goalie
          python -m pip install -e .

      - name: 'Lint'
        run: |
          . /home/firedrake/firedrake/bin/activate
          make lint

      - name: 'Test Goalie'
        run: |
          . /home/firedrake/firedrake/bin/activate
          python $(which firedrake-clean)
          export GITHUB_ACTIONS_TEST_RUN=1
          python -m coverage erase
          python -m coverage run -a --source=goalie -m pytest -v --durations=20 test
          python -m coverage run -a --source=goalie -m pytest -v --durations=10 test_adjoint
          python -m coverage report
