name: 'Run Goalie test suite'

on:
  # Run test suite whenever main is updated
  push:
    branches:
      - main

  # Run test suite whenever commits are pushed to an open PR
  pull_request:

  # Run test suite every Sunday at 1AM
  schedule:
    - cron: '0 1 * * 0'

concurrency:
  # Cancel jobs running if new commits are pushed
  group: >
    ${{ github.workflow }}-
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Test suite'
    runs-on: ubuntu-latest
    container:
      image: jwallwork/firedrake-parmmg:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2

      - name: 'Cleanup'
        if: ${{ always() }}
        run: |
          cd ..
          rm -rf build

      - name: 'Setup Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 'Install Goalie'
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip uninstall -y goalie
          python -m pip install -e .

      - name: 'Check citation'
        run: |
          . /home/firedrake/firedrake/bin/activate
          make check_citation

      - name: 'Lint'
        if: ${{ always() }}
        run: |
          . /home/firedrake/firedrake/bin/activate
          make lint

      - name: 'Test Goalie'
        run: |
          . /home/firedrake/firedrake/bin/activate
          python $(which firedrake-clean)
          export GITHUB_ACTIONS_TEST_RUN=1
          python -m coverage erase
          python -m coverage run -a --source=goalie -m pytest -v --durations=20 test
          python -m coverage run -a --source=goalie -m pytest -v --durations=10 test_adjoint
          python -m coverage report
